import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MVP AI Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid h-screen grid-cols-1 grid-rows-[auto_1fr_auto] place-content-stretch gap-2 bg-neutral-300 text-slate-600">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
